name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

env:
  COLLIDERML_DATA_DIR: ./data_cache

jobs:
  build:
    name: Build (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Prepare environment
        uses: ./.github/actions/setup-dev
        with:
          python-version: ${{ matrix.python-version }}

  lint:
    name: Lint (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Prepare environment
        uses: ./.github/actions/setup-dev
        with:
          python-version: ${{ matrix.python-version }}

      - name: Lint
        run: make lint

  test:
    name: Test (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
      - name: Prepare environment
        uses: ./.github/actions/setup-dev
        with:
          python-version: ${{ matrix.python-version }}

      - name: Obtain test data
        run: 
          uv colliderml download --dataset ttbar-pu200 --max-events 10 --output-dir ${COLLIDERML_DATA_DIR}

      - name: Test
        run: make test
